### ISSUE TITLE
Error while parsing

### ISSUE THREAD

**Issue by Falsen** [Bakkes/demoinfo-csgo-python#5]
I get this error when trying to parse my demo:

```
Traceback (most recent call last):
  File "test.py", line 136, in <module>
    hlfinder.parse()
  File "test.py", line 45, in parse
    self.demo.dump()
  File "/root/python/demo/demoinfocsgo/demodump.py", line 146, in dump
    self._handle_demo_packet()
  File "/root/python/demo/demoinfocsgo/demodump.py", line 255, in _handle_demo_packet
    self._dump_packet(buf, length)
  File "/root/python/demo/demoinfocsgo/demodump.py", line 267, in _dump_packet
    callback(cmd, data);
  File "/root/python/demo/demoinfocsgo/demodump.py", line 187, in _handle_gameevent
    name = self.descriptors[gameevent.eventid][1]
KeyError: 27
```

What could be the problem?

**Comment by wessonmo** [comment]
I have encountered a similar error:

```
Traceback (most recent call last):

  File "<ipython-input-2-e5342f9bf557>", line 3, in <module>
    hlfinder.parse()

  File "<ipython-input-1-6275463898fe>", line 48, in parse
    self.demo.dump()

  File "demoinfocsgo\demodump.py", line 146, in dump
    self._handle_demo_packet()

  File "demoinfocsgo\demodump.py", line 255, in _handle_demo_packet
    self._dump_packet(buf, length)

  File "demoinfocsgo\demodump.py", line 267, in _dump_packet
    callback(cmd, data);

  File "demoinfocsgo\demodump.py", line 191, in _handle_gameevent
    callback(event)

  File "<ipython-input-1-6275463898fe>", line 72, in player_spawn
    self.players[data.userid].is_alive = True

KeyError: 4
```

Any ideas?
